src/guidescanpy/flask/blueprints/info.py
import subprocess
from flask import jsonify, Blueprint
from guidescanpy import config, __version__

bp = Blueprint("info", __name__)


@bp.route("/supported", methods=["GET"])
def supported():
    result = subprocess.run([config.guidescan.bin, "--version"], stdout=subprocess.PIPE)
    guidescan_cli_version = result.stdout.decode("utf-8").strip()

    available = []
    available_dbs = config.json["guidescan"]["grna_database_path_map"]
    for organism, v in available_dbs.items():
        for enzyme, _ in v.items():
            available.append({"organism": organism, "enzyme": enzyme})

    return jsonify(
        {
            "version": __version__,
            "cli-version": guidescan_cli_version,
            "available": available,
        }
    )


@bp.route("/example_queries", methods=["GET"])
def example_queries():
    return jsonify(config.json["guidescan"]["example_queries"])


@bp.route("/example_sequences", methods=["GET"])
def example_sequences():
    return jsonify(config.json["guidescan"]["example_sequences"])

src/guidescanpy/flask/blueprints/job_library.py
import logging
from flask import Blueprint, jsonify, render_template, abort
from guidescanpy.tasks import app as tasks_app


bp = Blueprint("job_library", __name__)
logger = logging.getLogger(__name__)


@bp.route("/<job_id>")
def job(job_id):
    result = tasks_app.AsyncResult(job_id)
    return render_template("job_library.html", result=result)


@bp.route("/status/<job_id>")
def status(job_id):
    res = tasks_app.AsyncResult(job_id)
    return jsonify({"status": res.status})


@bp.route("/result/<format>/<job_id>")
def result(format, job_id):
    assert format in ("json",)
    res = tasks_app.AsyncResult(job_id)
    result = res.result

    match format:
        case "json":
            return jsonify(result)
        case _:
            abort(415)  # Unsupported Media Type

src/guidescanpy/flask/blueprints/job_query.py
import logging
from flask import Blueprint, jsonify, render_template, make_response, abort, request
import pandas as pd
from guidescanpy.tasks import app as tasks_app
from guidescanpy.flask.core.utils import job_result


bp = Blueprint("job_query", __name__)
logger = logging.getLogger(__name__)


@bp.route("/<job_id>")
@job_result
def job(job_id):
    result = tasks_app.AsyncResult(job_id)
    if result.status == "SUCCESS":
        # TODO: Is there a cleaner way to do this?
        first_region = (
            list(result.result["queries"].values())[0]["region"]
            if ("queries" in result.result) and result.result["queries"]
            else ""
        )
    else:
        first_region = ""
    return render_template("job_query.html", result=result, first_region=first_region)


@bp.route("/status/<job_id>")
def status(job_id):
    res = tasks_app.AsyncResult(job_id)
    return jsonify({"status": res.status})


def get_result(job_id, region=None, start=0, end=None, orderby=None, asc=True):
    """
    return a full result dictionary for non-DataTable use, a 'hits' dictionary for DataTable use.
    """
    result = tasks_app.AsyncResult(job_id).result

    if region is None:
        regions = result["queries"].keys()
    else:
        assert region in result["queries"], f"Region {region} not found in results"
        regions = [region]

    for region in regions:
        value = result["queries"][region]
        hits = pd.DataFrame(value["hits"])
        total_hits = len(hits)
        if orderby:
            hits.sort_values(by=orderby, ascending=asc, inplace=True)
        hits = hits[start:end]
        hits = hits.to_dict("records")

        result["queries"][region] = {
            "region": value["region"],
            "hits": hits,
            "total_hits": total_hits,
        }

    return result


@bp.route("/result/<format>/<job_id>", defaults={"offtarget": False})
@bp.route("/result/<format>/<offtarget>/<job_id>")
def result(format, job_id, offtarget):
    region = request.args.get("region")
    orderby = request.args.get("orderby")
    asc = request.args.get("asc") == "asc"
    start = int(request.args.get("start", 0))
    end = (
        int(request.args.get("limit")) + start
        if request.args.get("limit") is not None
        else None
    )
    result = get_result(job_id, region, start, end, orderby, asc)

    match format:
        case "json":
            return jsonify(result)

        case "bed":
            lines = ['track name="guideRNAs"']

            for _, v in result["queries"].items():
                for hit in v["hits"]:
                    chr = hit["coordinate"].split(":")[0]
                    start, end = hit["start"], hit["end"]
                    start -= 1  # convert from 1-indexed inclusive to 0-indexed inclusive; end remains unchanged
                    strand = hit["direction"]
                    region_string = hit["region-string"]
                    lines.append(f"{chr}\t{start}\t{end}\t{region_string}\t0\t{strand}")

            response = "\n".join(lines)
            response = make_response(response, 200)
            response.mimetype = "text/plain"
            return response

        case "csv":
            if offtarget:
                lines = [
                    "Region-name,gRNA-ID,gRNA-Seq,Number of off-targets,"
                    "Off-target summary,Off-target accession,Off-target chromosome,"
                    "Off-target direction,Off-target distance,Off-target position,"
                    "Off-target region-string,"
                    "Cutting efficiency,Specificity,GC,Rank,Coordinates,Strand,Annotations"
                ]
            else:
                lines = [
                    "Region-name,gRNA-ID,gRNA-Seq,Number of off-targets,"
                    "Off-target summary,Cutting efficiency,Specificity,GC,Rank,Coordinates,Strand,Annotations"
                ]

            for _, v in result["queries"].items():
                for i, hit in enumerate(v["hits"], start=1):
                    if offtarget:
                        n_off_targets = hit["n-off-targets"]
                        if n_off_targets == 0:
                            hit["off-targets"].append(
                                {
                                    "accession": "",
                                    "chromosome": "",
                                    "direction": "",
                                    "distance": "",
                                    "position": "",
                                    "region-string": "",
                                }
                            )
                        for off_target in range(max(1, n_off_targets)):
                            lines.append(
                                ",".join(
                                    str(x)
                                    for x in [
                                        hit["region-string"],
                                        hit["region-string"] + f".{i}",
                                        hit["sequence"],
                                        hit["n-off-targets"],
                                        hit["off-target-summary"],
                                        hit["off-targets"][off_target]["accession"],
                                        hit["off-targets"][off_target]["chromosome"],
                                        hit["off-targets"][off_target]["direction"],
                                        hit["off-targets"][off_target]["distance"],
                                        hit["off-targets"][off_target]["position"],
                                        hit["off-targets"][off_target]["region-string"],
                                        hit["cutting-efficiency"],
                                        hit["specificity"],
                                        hit["gc-content"],
                                        i,
                                        hit["coordinate"],
                                        hit["direction"],
                                        hit["annotations"],
                                    ]
                                )
                            )
                        if n_off_targets == 0:
                            hit["off-targets"] = []
                    else:
                        lines.append(
                            ",".join(
                                str(x)
                                for x in [
                                    hit["region-string"],
                                    hit["region-string"] + f".{i}",
                                    hit["sequence"],
                                    hit["n-off-targets"],
                                    hit["off-target-summary"],
                                    hit["cutting-efficiency"],
                                    hit["specificity"],
                                    hit["gc-content"],
                                    i,
                                    hit["coordinate"],
                                    hit["direction"],
                                    hit["annotations"],
                                ]
                            )
                        )

            response = "\n".join(lines)
            response = make_response(response, 200)
            response.mimetype = "text/csv"
            return response

        case _:
            abort(415)  # Unsupported Media Type


@bp.route("/result/dt/<job_id>")
def result_dt(job_id):
    region = request.args.get("region")
    assert (
        region is not None
    ), "DataTables format only supported when region is specified"

    # Get sorting parameters
    orderby = request.args.get("order[0][column]")  # Default is 5.
    if orderby is not None:
        orderby = request.args.get("columns[" + orderby + "][data]")
    asc = request.args.get("order[0][dir]") == "asc"  # Default is 'desc'

    # Get pagination parameters
    page = int(request.args.get("page", 1))
    per_page = int(request.args.get("per_page", 10))
    start = (page - 1) * per_page
    end = start + per_page

    result = get_result(job_id, region, start, end, orderby, asc)
    data = result["queries"][region]
    hits, total_hits = data["hits"], data["total_hits"]

    response = {
        "data": hits,
        "draw": int(request.args.get("draw", 1)),
        "recordsTotal": total_hits,
        "recordsFiltered": total_hits,
    }
    return jsonify(response)

src/guidescanpy/flask/blueprints/job_sequence.py
import logging
from flask import Blueprint, jsonify, render_template
from guidescanpy.tasks import app as tasks_app
from guidescanpy.flask.core.utils import job_result


bp = Blueprint("job_sequence", __name__)
logger = logging.getLogger(__name__)


@bp.route("/<job_id>")
@job_result
def job(job_id):
    result = tasks_app.AsyncResult(job_id)
    return render_template("job_sequence.html", result=result)


@bp.route("/status/<job_id>")
def status(job_id):
    res = tasks_app.AsyncResult(job_id)
    return jsonify({"status": res.status})

src/guidescanpy/flask/blueprints/web.py
import logging
import os.path
from flask import (
    current_app,
    Blueprint,
    request,
    render_template,
    redirect,
    url_for,
)
import requests
from werkzeug.utils import secure_filename
from guidescanpy.flask.blueprints.query import query_endpoint
from guidescanpy.flask.blueprints.sequence import sequence_endpoint
from guidescanpy.flask.blueprints.library import library_endpoint

bp = Blueprint("web", __name__)
logger = logging.getLogger(__name__)


def allowed_file(filename):
    return "." in filename and os.path.splitext(filename)[-1] in (
        ".txt",
        ".bed",
        ".gtf",
        ".gff",
    )


@bp.route("/")
def index():
    return redirect(url_for("web.grna_design"))


@bp.route("/grna_design", methods=["GET", "POST"])
def grna_design():
    if request.method == "POST":
        form = request.form
        form_data = {
            "organism": form["selectOrganism"],
            "enzyme": form["selectEnzyme"],
            "query-text": form["txtCoordinates"],
            "filter-annotated": form.get("checkExonic", "off") == "on",
            "mode": "flanking"
            if form.get("checkFlanking", "off") == "on"
            else "within",
        }

        if form.get("checkFlanking", "off") == "on":
            form_data["flanking"] = int(form["txtFlanking"])

        if form.get("checkTopN", "off") == "on":
            form_data["topn"] = int(form["txtTopN"])

        if file := request.files.get("fileCoordinates"):
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                filepath = os.path.join(current_app.config["UPLOAD_FOLDER"], filename)
                file.save(filepath)
                form_data["file"] = filepath

        if form.get("checkFilterAboveSpecificity", "off") == "on":
            form_data["s-bounds-l"] = float(form["txtFilterAboveSpecificity"])
            form_data["s-bounds-u"] = 1.0

        if form.get("checkFilterAboveCE", "off") == "on":
            form_data["ce-bounds-l"] = float(form["txtFilterAboveCE"])
            form_data["ce-bounds-u"] = 1.0

        if form.get("checkFilterGCContent", "off") == "on":
            form_data["gc-bounds-l"] = float(form["txtFilterAboveGCContent"])
            form_data["gc-bounds-u"] = float(form["txtFilterBelowGCContent"])

        if form.get("checkFilterGRNAPattern", "off") == "on":
            form_data["pattern_avoid"] = form["txtFilterGRNAPattern"]

        results = query_endpoint(form_data)
        return results

    return render_template("grna_design.html")


@bp.route("/gene_targeting_library", methods=["GET", "POST"])
def gene_targeting_library():
    if request.method == "POST":
        form = request.form
        form_data = {
            "organism": form["selectOrganism"],
            "append5": form.get("checkAppend5", "off") == "on",
            "genes": form["txtGenes"],
        }

        if form.get("checkPool", "off") == "on":
            form_data["n_pools"] = int(form["txtPool"])
        if form.get("checkNGuides", "off") == "on":
            form_data["n_guides"] = int(form["txtNGuides"])
        if form.get("checkPEG", "off") == "on":
            form_data["frac_essential"] = float(form["txtPEG"])
        if form.get("checkPCG", "off") == "on":
            form_data["frac_control"] = float(form["txtPCG"])

        results = library_endpoint(form_data)
        return results

    return render_template("gene_targeting_library.html")


@bp.route("/grna_sequence_search", methods=["GET", "POST"])
def grna_sequence_search():
    if request.method == "POST":
        form = request.form
        enzyme = form["selectEnzyme"]
        if enzyme == "None":
            enzyme = None

        form_data = {
            "organism": form["selectOrganism"],
            "enzyme": enzyme,
            "mismatches": int(form["selectMismatches"]),
            "sequences": form["txtSequence"],
        }
        results = sequence_endpoint(form_data)
        return results

    return render_template("grna_sequence_search.html")


@bp.route("/about")
def about():
    return render_template("about.html")


@bp.route("/downloads")
def downloads():
    return render_template("downloads.html")


@bp.route("/contact")
def contact():
    return render_template("contact.html")


@bp.route("/feedback")
def feedback():
    return render_template("feedback.html")


@bp.route("/submit_feedback", methods=["POST"])
def submit_feedback():
    # Validate Google Form configuration
    FORM_ID = os.getenv("FEEDBACK_FORM_ID")
    if not FORM_ID:
        return {"message": "Feedback form not found."}, 500
    FORM_URL = f"https://docs.google.com/forms/d/e/{FORM_ID}/formResponse"

    ENTRY_TYPE = os.getenv("FEEDBACK_ENTRY_TYPE")
    ENTRY_QUERY = os.getenv("FEEDBACK_ENTRY_QUERY")
    ENTRY_OVERALL = os.getenv("FEEDBACK_ENTRY_OVERALL")
    ENTRY_FEATTYPE = os.getenv("FEEDBACK_ENTRY_FEATTYPE")
    ENTRY_DESC = os.getenv("FEEDBACK_ENTRY_DESC")
    ENTRY_ALT = os.getenv("FEEDBACK_ENTRY_ALT")
    ENTRY_EMAIL = os.getenv("FEEDBACK_ENTRY_EMAIL")

    for entry in [
        ENTRY_TYPE,
        ENTRY_QUERY,
        ENTRY_OVERALL,
        ENTRY_FEATTYPE,
        ENTRY_DESC,
        ENTRY_ALT,
        ENTRY_EMAIL,
    ]:
        if not entry:
            return {"message": "Feedback form entries not found."}, 500

    # Required fields
    selectFeedbackType = request.form.get("selectFeedbackType")
    selectFeedbackOverall = request.form.get("selectFeedbackOverall")
    txtDescription = request.form.get("txtDescription")
    # Conditionally required field
    selectFeedbackFeatureType = request.form.get("selectFeedbackFeatureType")

    # Validate required fields
    if not selectFeedbackType or not selectFeedbackOverall or not txtDescription:
        return {"message": "Please fill out all required fields."}, 400
    if selectFeedbackType == "Feature request" and not selectFeedbackFeatureType:
        return {"message": "Please fill out all required fields."}, 400

    # Mapping from form fields to Google Form entry IDs
    data = {
        ENTRY_TYPE: selectFeedbackType,
        ENTRY_QUERY: request.form.get("txtFeedbackQueryId"),
        ENTRY_OVERALL: selectFeedbackOverall,
        ENTRY_FEATTYPE: selectFeedbackFeatureType,
        ENTRY_DESC: txtDescription,
        ENTRY_ALT: request.form.get("txtAlternative"),
        ENTRY_EMAIL: request.form.get("txtFeedbackEmail"),
    }

    # Submit form data
    response = requests.post(FORM_URL, data=data)
    if response.status_code == 200:
        return {"message": "Thank you for your feedback!"}, 200
    else:
        return {
            "message": "There was an error submitting your feedback. Please try again."
        }, 500

src/guidescanpy/flask/templates/job_library.html
{% extends "job.html" %}

{% block main %}
    {{ super() }}
    {% if result.status == 'SUCCESS' %}
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <div class="card">
                        <h5 class="card-header">Job {{ result.task_id }}</h5>
                        <div class="card-body text-center">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Download Results
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item"
                                       href="{{ url_for('job_library.result', format='json', job_id=result.task_id) }}">as
                                        json..</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

src/guidescanpy/flask/templates/job_query.html
{% extends "job.html" %}

{% block main %}
    {{ super() }}
    {% if result.status == 'SUCCESS' %}
        <div id="modal-off-targets" class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <div id="modal-title" class="modal-title"></div>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div id="div-off-targets">
                            <table id="table-off-targets" class="display datatable" style="width: 100%;"></table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <div class="card">
                        <h5 class="card-header">Job {{ result.task_id }}</h5>
                        <div class="card-body text-center">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button"
                                        id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Download Results
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item"
                                       href="{{ url_for('job_query.result', format='json', job_id=result.task_id) }}">as
                                        json..</a>
                                    <a class="dropdown-item"
                                       href="{{ url_for('job_query.result', format='csv', job_id=result.task_id) }}">as
                                        csv..</a>
                                    <a class="dropdown-item"
                                       href="{{ url_for('job_query.result', format='csv', job_id=result.task_id, offtarget=True) }}">as
                                        csv (off-target info included)..</a>
                                    <a class="dropdown-item"
                                       href="{{ url_for('job_query.result', format='bed', job_id=result.task_id) }}">as
                                        bed..</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% if first_region != "" %}
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <h5 class="card-header">IGV Viewer</h5>
                            <div class="card-body">
                                <div id="igv-div"></div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <h5 class="card-header">Job {{ result.task_id }}</h5>
                            <div class="card-body">
                                No results for query region(s).
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}

            {% for region, values in result.result['queries'].items() %}
                {% if values['hits']|length > 0 %}
                    <div class="row">
                        <div class="col">
                            <div class="card">
                                <h5 class="card-header">{{ region }}</h5>
                                <div class="card-body">
                                    <table class="display datatable resulttable" data-region="{{ region }}">
                                        <thead>
                                        <tr>
                                            <th>coordinate</th>
                                            <th>sequence</th>
                                            <th>num-off-targets</th>
                                            <th>off-target-summary</th>
                                            <th>cutting-efficiency</th>
                                            <th>specificity</th>
                                            <th>gc-content</th>
                                            <th>annotations</th>
                                            <th>off-targets-hidden</th>
                                        </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

        </div>


    {% endif %}
{% endblock %}

{% block head %}
    {{ super() }}
    {% if result.status == 'SUCCESS' %}
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css"/>
    {% endif %}
{% endblock %}

{% block js %}
    {{ super() }}
    {% if result.status == 'SUCCESS' %}
        {% if first_region != "" %}
            <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/igv@2.15.5/dist/igv.min.js"></script>
            <script type="text/javascript" charset="utf-8">
                $(document).ready(function () {
                    var igvDiv = document.getElementById("igv-div");
                    var options =
                        {
                            genome: "{{ result.result['organism'] }}",
                            locus: "{{ first_region }}",
                            tracks: [
                                {
                                    "url": window.location.origin + "{{ url_for('job_query.result', format='bed', job_id=result.task_id) }}",
                                    "format": "bed"
                                }
                            ]
                        };
                    igv.createBrowser(igvDiv, options);

                    $('.resulttable').each(function () {
                        var region = $(this).data('region');
                        var table = $(this).DataTable({
                            searching: false,
                            lengthChange: false,
                            bInfo: false,
                            pagingType: "numbers",
                            serverSide: true,
                            order: [[5, 'desc']],
                            ajax: {
                                url: "{{url_for('job_query.result_dt', job_id=result.task_id)}}",
                                data: function (d) {
                                    d.page = Math.ceil(d.start / d.length) + 1;
                                    d.per_page = 10;
                                    d.region = region;
                                }
                            },
                            columns: [
                                {
                                    data: 'coordinate',
                                    render: function (data) {
                                        return '<a target="_blank" href="https://igv.org/app/?genome={{ result.result['organism'] }}&locus=' + data + '">' + data + '</a>';
                                    }
                                },
                                {
                                    data: 'sequence'
                                },
                                {
                                    data: 'n-off-targets'
                                },
                                {
                                    data: 'off-target-summary',
                                    render: function (data, type, row) {
                                        if (row['n-off-targets'] > 0) {
                                            return '<a href="#" class="off_target">' + data + '</a>';
                                        } else {
                                            return data;
                                        }
                                    }
                                },
                                {
                                    data: 'cutting-efficiency',
                                    render: function (data) {
                                        return data.toFixed(2);
                                    }
                                },
                                {
                                    data: 'specificity',
                                    render: function (data) {
                                        return data.toFixed(2);
                                    }
                                },
                                {
                                    data: 'gc-content',
                                    render: function (data) {
                                        return data.toFixed(2);
                                    }
                                },
                                {
                                    data: 'annotations',
                                    orderable: false
                                },
                                {
                                    data: 'off-targets',
                                    render: function (data) {
                                        return JSON.stringify(data);
                                    },
                                    visible: false
                                },
                            ]
                        });

                        $('.datatable tbody').on('click', 'a[class="off_target"]', function (event) {
                            event.preventDefault();
                            var row = table.row($(this).parents('tr')).data();
                            $('#modal-title').html('Off-targets for ' + row['coordinate']);
                            $('#table-off-targets').DataTable({
                                data: JSON.parse(JSON.stringify(row['off-targets'])),
                                columns: [
                                    {
                                        data: 'region-string',
                                        title: 'coordinates',
                                        render: function (data, type, row, meta) {
                                            return '<a target="_blank" href="https://igv.org/app/?genome={{ result.result['organism'] }}&locus=' + data + '">' + data + '</a>';
                                        }
                                    },
                                    {data: 'distance', title: 'distance'}
                                ],
                                searching: false,
                                lengthChange: false,
                                bInfo: false,
                                pagingType: "numbers",
                                destroy: true
                            });
                            $('#modal-off-targets').modal('show');
                        });
                    });
                });
            </script>
        {% endif %}
    {% endif %}
{% endblock %}